# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.

steps:
# This step builds the container image.
- id: Build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/lei-app:${SHORT_SHA}', '.']
  timeout: 500s

# This step pushes the image to Container Registry
- id: Push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/lei-app:${SHORT_SHA}']

- id: Change image
  name: 'gcr.io/$PROJECT_ID/kustomize'
  dir: 'cicd/kustomize/base'
  args: ['edit', 'set', 'image', 'lei-app=gcr.io/${PROJECT_ID}/lei-app:${SHORT_SHA}']

# This step deploys the new version of our container image
# in the hello-cloudbuild Kubernetes Engine cluster.
- id: Deploy
  name: 'gcr.io/$PROJECT_ID/kustomize'
  args: ['build', 'cicd/kustomize/overlays/dev']
  env:
    - 'APPLY=true'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=lei-ikala-cluster-1'
    - 'GCLOUD_PROJECT=${PROJECT_ID}'
