apiVersion: apps/v1
kind: Deployment
metadata:
  name: lei-app
  labels:
    app: lei-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lei-app
  template:
    metadata:
      labels:
        app: lei-app
    spec:
      containers:
        - name: lei-app
          image: lei-app
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
